### ISSUE TITLE
Title Bar Use

### ISSUE THREAD

**Issue by cjbarth** [jujinkim/Frequaw-issue#2]
It would be nice if the title bar were actually a link to open the widget settings. Many other apps work that way and I keep tapping it and waiting. Then I realize what won't happen and then have to go to my app drawer. Since the point of this app is, in part, to stay out of the app drawer, this seems like a sensible addition.

**Comment by jujinkim** [comment]
Users can access each widget's settings via the widget configuration button.
Most people rarely enter the setting page after they set everything, so I have decided to close this issue without any modification. Thank you.
