### ISSUE TITLE
Option to show the recently openend

### ISSUE THREAD

**Issue by Karut** [jujinkim/Frequaw-issue#4]
Thank you for creating this widget! More than wanting to access the most frequently used apps I would like to access the recently used apps in a widget. I would find that easier than going to the native recently used menu to access the apps.

**Comment by jujinkim** [comment]
Thanks for your suggestion!

**Comment by cjbarth** [comment]
I might suggest that there be an option to make just the last row an MRU list and the rest be MFU. There are lots of MRU widgets out there, so I really have come to depend on the MFU features of this app. @Karut , you might consider just using a different widget while waiting for something to happen here. You could even both both Frequaw and [Most Recently Used](https://play.google.com/store/apps/details?id=day.cloudy.apps.mru&hl=en_US&gl=US) on the same page of your launcher to get the effect you're looking for.

**Comment by jujinkim** [comment]
This feature will be included at the next version. Not perfectly works because of the widget updating performance, but anyway it will come to the next version.

**Comment by Karut** [comment]
Thanks, I am using it now. Performance is good enough for me :)
